### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by Skeptron** [vrd/js-intersect#2]
Hi _again_!

The intersect() method is caught in infinite loops sometimes... Works with these 2 polygons : 

    var poly0 = [
      {x: 1000, y: 800},
      {x: 800, y: 500},
      {x: 600, y: 500},
      {x: 474, y: 800},
      {x: 1000, y: 800}
    ];

    var poly1 = [
      {x: 1000, y: 400},
      {x: 400, y: 200},
      {x: 200, y: 200},
      {x: 200, y: 300},
      {x: 449, y: 800},
      {x: 1000, y: 800}
    ];

Any idea why those 2 particular polygons would cause that?

Thanks!

**Comment by vrd** [comment]
Problem is definitely in first polygon that has two consecutive identical points (first and last). This points create edge with zero length and this is unexpected for algorithm. Remove last (or first) point in poly0 and all will work. Anyway, I'll add check to identify such cases and remove duplicated points.

**Comment by Skeptron** [comment]
Ok nice! Thanks a lot!
