### ISSUE TITLE
Intesection on some polygons not detected

### ISSUE THREAD

**Issue by clemosm** [vrd/js-intersect#6]
Hello,
I'm using this script for a project and it's very useful, however it seems to have issues with some polygons (or maybe I do something wrong). Here is an example of two intersecting polygons where the script doesn't find any intersection : 

[{x:-38383.11684890961,y:975822.2939549877},{x:-38383.08019699532,y:975824.4200341334},{x:-38381.523363302535,y:975824.3935903418},{x:-38381.46925809573,y:975827.5166057295},{x:-38379.9211510492,y:975827.4901618769},{x:-38378.91933205856,y:975827.4742955655},{x:-38379.01183450892,y:975822.2278456159},{x:-38380.21087570504,y:975822.2463562398},{x:-38380.18120510776,y:975823.9942891567},{x:-38380.844430223515,y:975824.0075110482},{x:-38380.874100820794,y:975822.2542893642}]

[{x:-38383.08019699532,y:975824.4200341334},{x:-38381.523363302535,y:975824.3935903418},{x:-38380.823486272486,y:975824.3909459626},{x:-38380.844430223515,y:975824.0075110482},{x:-38380.874100820794,y:975822.2542893642},{x:-38383.11684890961,y:975822.2939549877}]

![image](https://user-images.githubusercontent.com/50964440/117282893-86b6f800-ae65-11eb-8ef7-07d3a80b5558.png)

Hope someone can help me with that

**Comment by vrd** [comment]
I made some fixes and now your example should work. Please check and reply.

**Comment by clemosm** [comment]
It works perfectly now, thank you very much !
