### ISSUE TITLE
Zero area with seemingly overlapping polygons 

### ISSUE THREAD

**Issue by northernstream** [vrd/js-intersect#8]
Hi!

Here are two polygons that should overlap but seem to return area=0 / zero nodes for intersect call. 

![bild](https://user-images.githubusercontent.com/37591857/157481203-21bf118d-81af-42fd-acbe-763ebda1d056.png)

When calling `var result = intersect(smallcircle, largehalfcircle)` it returns 0 while some polygon of some size would be expected.

The polygons looks like this in array form:

smallcircle=[
  { x: 10, y: 0 },
  { x: -10, y: 1.2246467991473533e-15 },
  { x: -10, y: 1.2246467991473533e-15 },
  { x: -9.92546151641322, y: 1.2186934340514755 },
  { x: -9.702957262759965, y: 2.4192189559966772 },
  { x: -9.335804264972015, y: 3.5836794954530067 },
  { x: -8.82947592858927, y: 4.694715627858907 },
  { x: -8.191520442889919, y: 5.73576436351046 },
  { x: -7.431448254773944, y: 6.691306063588581 },
  { x: -6.560590289905072, y: 7.547095802227721 },
  { x: -5.591929034707467, y: 8.290375725550417 },
  { x: -4.5399049973954675, y: 8.910065241883679 },
  { x: -3.420201433256687, y: 9.396926207859085 },
  { x: -2.249510543438648, y: 9.743700647852352 },
  { x: -1.0452846326765333, y: 9.945218953682733 },
  { x: 0.174524064372836, y: 9.998476951563912 },
  { x: 1.3917310096006545, y: 9.902680687415703 },
  { x: 2.5881904510252074, y: 9.659258262890683 },
  { x: 3.746065934159122, y: 9.271838545667872 },
  { x: 4.848096202463371, y: 8.746197071393958 },
  { x: 5.877852522924732, y: 8.090169943749475 },
  { x: 6.819983600624985, y: 7.313537016191704 },
  { x: 7.66044443118978, y: 6.4278760968653925 },
  { x: 8.386705679454241, y: 5.44639035015027 },
  { x: 8.98794046299167, y: 4.383711467890774 },
  { x: 9.455185755993169, y: 3.255681544571567 },
  { x: 9.781476007338057, y: 2.079116908177593 },
  { x: 9.961946980917455, y: 0.8715574274765816 },
  { x: 10, y: 0 }
]
largehalfcircle=[
  { x: -3.4641016151399997, y: 3.6399999999999997 },
  { x: -2.7767585183349683, y: 3.5979602952570557 },
  { x: -2.099662123957873, y: 3.47246789619662 },
  { x: -1.4429063797045063, y: 3.265393605444218 },
  { x: -0.816282001027576, y: 2.979824423724347 },
  { x: -0.22913051412010077, y: 2.620017529789913 },
  { x: 0.30979500472396015, y: 2.1913368156925035 },
  { x: 0.7924604173164336, y: 1.70017292350646 },
  { x: 1.211670294070434, y: 1.1538479755750122 },
  { x: 1.5611751812823944, y: 0.5605064185310433 },
  { x: 1.8357647660925234, y: -0.07100639164322864 },
  { x: 2.031345550248726, y: -0.7312760535006015 },
  { x: 2.1450018747370607, y: -1.4104594671704347 },
  { x: 2.1750393855420467, y: -2.0984315723062843 },
  { x: 2.1210102925624557, y: -2.7849362894147713 },
  { x: 1.9837200451303452, y: -3.4597394143782165 },
  { x: 1.7652153246166802, y: -4.112781186865746 },
  { x: 1.468753533126192, y: -4.7343262581893395 },
  { x: 1.0987542331347027, y: -5.315108822929549 },
  { x: 0.6607332619921222, y: -5.84647075075249 },
  { x: 0.16122050349208106, y: -6.320490659191036 },
  { x: -0.3923374576552501, y: -6.730102003212193 },
  { x: -0.9916883472496036, y: -7.069198421127302 },
  { x: -1.6278972240016387, y: -7.332724766380148 },
  { x: -2.2914796789278418, y: -7.516752468138664 },
  { x: -2.97254322604321, y: -7.618538097237445 },
  { x: -3.6609347765421094, y: -7.636564264387699 },
  { x: -4.3463919979669035, y: -7.570562240956576 },
  { x: -5.018696301947874, y: -7.4215159650921185 },
  { x: -5.667825179819504, y: -7.1916473734717625 },
  { x: -6.284101615140003, y: -6.884383277344233 },
  { x: -6.858338345717552, y: -6.504304276666732 },
  { x: -7.381974824528745, y: -6.057076473909991 },
  { x: -7.847204837757316, y: -5.549367005521084 },
  { x: -8.247092877462244, y: -4.988744650275275 },
  { x: -8.575677534026706, y: -4.383566996217544 },
  { x: -8.828060367044666, y: -3.742855848274705 },
  { x: -9.000478929784824, y: -3.076162733923712 },
  { x: -9.09036285860541, y: -2.393426511916864 },
  { x: -9.096372191155796, y: -1.7048252067897969 },
  { x: -9.018417342128853, y: -1.0206242779585133 },
  { x: -8.85766043877152, y: -0.3510235853637631 },
  { x: -8.616497996244268, y: 0.2939946669475142 },
  { x: -8.298525191099912, y: 0.9048147424927064 },
  { x: -7.908482265481911, y: 1.4723307208367133 },
  { x: -7.452183861032127, y: 1.988082245892128 },
  { x: -6.936432335976713, y: 2.4443806503419117 },
  { x: -6.368916357632706, y: 2.8344235759599137 },
  { x: -5.758096282087513, y: 3.1523963811042695 },
  { x: -5.113078029776235, y: 3.39355882363152 },
  { x: -4.443477337181487, y: 3.554315726988853 },
  { x: -3.7592764083502024, y: 3.632270576015796 },
  { x: -3.4641016151399997, y: 3.6399999999999997 }
]

Thanks for your help!

Sincere Regards
Marcus

**Comment by northernstream** [comment]
Added info, It seems that parallel lines have something to do with it. If you take the lower line in the big half circle which goes from 0 to 180 degrees and shift the line with just one degree at either end of the half circle, the algorithm seems to work and a polygon with area is produced.

**Comment by vrd** [comment]
@northernstream Please check if issue still exists. By the way, in your example fig1 has two zero-length edges and fig2 has one zero-length edge. Despite it is working for this example I do not recommend to use polygons with zero-length edges, it can cause unexpected side effects.

**Comment by northernstream** [comment]
@vrd Thank you it worked perfectly, noted had that as an extra safety measure while numerically integrating.  Brilliant work! :)
